spring.application.name=finetrack_backend

server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/finetrack
spring.datasource.username=postgres
spring.datasource.password=163204

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=finetracksupersecretkeyfinetracksupersecretkey
jwt.expiration=86400000
